apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名称必须与下面的 spec 字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: demos.example.com
spec:
  group: example.com
  names:
    plural: demos
    singular: demo
    kind: Demo
    shortNames:
    - dm
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
#                  pattern: "^test$"
      additionalPrinterColumns:
      - name: CR-Name
        type: string
        jsonPath: .spec.name
